# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jamming.Y's Site
email: 3922909893@qq.com
description: |- 
  Welcome to Jamming.Y's world! 
  I'm an underguaduate student majoring in Information and Computing Science at EECS,PKU.
  My research interests now especially lies in Computer Vision.
  It is my great fortune to work as an undergraduate intern at the Spatial and Temporal Restoration, Understanding and Compression Team (STRUCT) of Wangxuan Institute of Computer Technology (WICT), mentored by Prof. Jiaying Liu.
  I love many kinds of sports, including football, basketball, badminton, table tennis, and running.
  I'm also a big fan of Atletico de Madrid.
  I love music, but not such an expert.
  I'm looking forward to sharing my thoughts and experiences with you!

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://j-am-ack.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Jam Y
twitter_username: AtletiJam60739
github_username:  J-am-ack



# Build settings

theme: minima
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
permalink: /blog/:year/:month/:day/:title/  # 文章URL格式
paginate: 5  # 每页显示5篇文章
paginate_path: /blog/page:num/


nav:
  - title: 首页
    url: /
  - title: 关于
    url: /about/
  - title: 博客
    url: /blog/
  - title: 友链
    url: /friends/
  - title: 访问统计
    url: /stats/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



friends:
  - name: "xisenal"
    url: "https://xisenal.github.io/"
    avatar: friends\avatars\xisanal.jpg
    description: "西瓜qwq"
  - name: "dasai-hzm"
    url: "https://hzmsailor.com/"
    avatar: friends\avatars\hzm.png
    description: "session"
  - name: "TRpuppy"
    url: "https://trpuppy.vercel.app/"
    avatar: friends\avatars\xq.png
    description: "谦哥yyds"
  - name: "Jing Xu's Site"
    url: "https://iculizhi.github.io/"
    avatar: friends\avatars\xj.jpg
    description: "上士闻道，勤而行之"
  



kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  entity_output: as_char  # 避免特殊字符被转义
  toc_levels: 1..6
  table_of_contents:
    enable: true


disqus:
  shortname: https-j-am-ack-github-io

utterances:
  repo: J-am-ack/J-am-ack.github.io